using Tyuiu.IvanovEO.Sprint1.Task1.V20.Lib;
Console.Title = "Спринт #1 | Выполнил: Иванов Е. О. | ПИНб-25-1";
Console.WriteLine("***************************************************************************");
Console.WriteLine("* Спринт #1                                                               *");
Console.WriteLine("* Тема: Базовые навыки работы в C#                                        *");
Console.WriteLine("* Задание #1                                                              *");
Console.WriteLine("* Вариант #20                                                             *");
Console.WriteLine("* Выполнил: Иванов Евгений Олегович | ПИНб-25-1                           *");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* УСЛОВИЕ:                                                                *");
Console.WriteLine("*Написать консольную программу на C#, которая вычисляет данное выражение и ");
Console.WriteLine("*   выводит на экран значение выражения                                   *");
Console.WriteLine("* УСЛОВИЕ:                                                               *");
Console.WriteLine("Введите x: ");
double x = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Введите y: ");
double y = Convert.ToDouble(Console.ReadLine());
DataService ds= new DataService();
Console.WriteLine("Результат = " + ds.Calculate(x, y));